# @format

#index:
#    path: /
#    controller: App\Controller\DefaultController::index

register:
  path: /register
  controller: App\Controller\AuthApiController::register
  methods: [GET, POST]

authentication_token:
  path: /authentication_token
  methods: ["POST"]

swagger_ui:
  path: /docs
  controller: api_platform.swagger.action.ui
